SDT-649Fix: se corriegieron observaciones
subsesjal/siiges-ui pull request #204
Opened 2024-08-09 22:42 UTC by joe2141

Se han corregido botones, secciones y titulos

2024-08-09 23:37 UTC, robertotorres-dev commented on packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
en que punto se cambio esto ? es para todas las secciones?

2024-08-09 23:38 UTC, robertotorres-dev commented on packages/solicitudes/src/components/ModuleSelector/NuevaSolicitud/index.jsx
>          </Grid>
Esto en que pantalla se cambia?

2024-08-09 23:38 UTC, robertotorres-dev commented on packages/shared/src/components/Navbar/MenuNavbar.jsx
>              <ListItemIcon>
porque se comenta esta parte?

2024-08-09 23:39 UTC, robertotorres-dev commented on packages/shared/src/components/Buttons/ButtonsForm.jsx
> +          </ButtonUnstyled>
en que punto se cambió por confirmar? que pantallas son afectadas?

2024-08-09 23:39 UTC, robertotorres-dev requested changes
observaciones hechas en código

2024-08-13 21:02 UTC, joe2141 commented on packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
Sí, se cambió en todas las secciones

2024-08-13 21:15 UTC, joe2141 commented on packages/solicitudes/src/components/ModuleSelector/NuevaSolicitud/index.jsx
>          </Grid>
Cuando creas la solciitud
![imagen](https://github.com/user-attachments/assets/19d15344-c753-4419-b004-7373835f8b91)

2024-08-13 21:16 UTC, joe2141 commented on packages/shared/src/components/Navbar/MenuNavbar.jsx
>              <ListItemIcon>
Quite el botón de ajustes
![imagen](https://github.com/user-attachments/assets/d9840edf-0755-44fd-80a7-acdb56b44779)

2024-08-14 16:14 UTC, robertotorres-dev commented on packages/shared/src/components/Buttons/ButtonsForm.jsx
> +      )}
No agregar la condición, solo cambiar el texto Guardar

2024-08-14 16:16 UTC, robertotorres-dev commented on packages/solicitudes/src/components/Sections/AsignaturasFormacionElectiva.jsx
>        />
Formación

2024-08-15 20:49 UTC, elmejorlui commented on apps/siiges-app/pages/notificaciones/index.jsx
seguro que esa tabla no necesita titulo?

2024-08-15 20:50 UTC, elmejorlui commented on packages/shared/src/components/Buttons/ButtonsForm.jsx
deshabilitar proptypes es algo que no hacemos, porque le rompe el corazón a Esau

2024-08-15 21:40 UTC, elmejorlui approved these changes
lgbtq+

2024-08-18 23:19 UTC, robertotorres-dev commented on packages/shared/src/components/Buttons/ButtonsForm.jsx
> +            className="buttonAdd guardar"
esto no es necesario

2024-08-18 23:20 UTC, robertotorres-dev commented on packages/solicitudes/src/components/SectionLayout/ButtonSection.jsx
> -    : 'Terminar Sección';
En que quedaron con esto? no se que no se iba a cambiar?

2024-08-19 22:12 UTC, robertotorres-dev approved these changes

2024-08-20 21:50 UTC, merged