feat(FDA02): falta representante diligencias
subsesjal/siiges-ui pull request #86
Opened 2023-10-24 17:57 UTC by joe2141

Se corrigiron observaciones del FDA01 y FDA02 
Del FDA01 y FDA02 solo faltan los datos de representante legal
Y del FDA02 tener un diligente para hacer unas pruebas

2023-10-24 21:56 UTC, robertotorres-dev commented on apps/siiges-app/pages/solicitudes/detallesSolicitudes/FDA/FDA02/index.jsx
> +  ];
renombrar tabla para que sea más específica

2023-10-24 21:57 UTC, robertotorres-dev requested changes

2023-10-24 21:57 UTC, robertotorres-dev commented on apps/siiges-app/pages/solicitudes/detallesSolicitudes/FDA/FDA02/index.jsx
> +      ['LICENCIATURA director', 'MEDIOS MASIVOS DE COMUNICACIÓN director'],
renombrar tabla para que sea más específica

2023-10-24 21:57 UTC, robertotorres-dev commented on apps/siiges-app/pages/solicitudes/detallesSolicitudes/FDA/FDA02/index.jsx
> +    'NOMBRES PROPUESTOS PARA LA INSTITUCIÓN EDUCATIVA',
renombrar sección para que sea más específica

2023-10-24 21:57 UTC, robertotorres-dev commented on apps/siiges-app/pages/solicitudes/detallesSolicitudes/FDA/FDA02/index.jsx
> +      ['NOMBRE PROPUESTO No. 1', 'CENTRO EDUCATIVO EL SALTO'],
renombrar tabla para que sea más específica

2023-10-24 23:16 UTC, robertotorres-dev approved these changes

2023-10-25 16:05 UTC, elmejorlui approved these changes
LGTM

2023-10-25 16:08 UTC, merged